version: "3.8"
services:
  citibank:
    build: .
    container_name: citibank
    image: citibank
    volumes:
      - $HOME/.config/gcloud:/root/.config/gcloud
      - ./src/citibank:/app/citibank
    env_file:
      .env
